# Generated by Django 5.1.6 on 2026-03-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('definition', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('definition', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PoleActivitesProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('objectif', models.CharField(max_length=256)),
                ('caracterisation', models.TextField()),
                ('capacite', models.TextField()),
                ('habilete', models.TextField()),
                ('verbe', models.TextField()),
                ('critere_evalusation', models.TextField()),
                ('exemple', models.TextField()),
            ],
            options={
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='TypeActivitePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteProfessionnelleMoyenRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_ressource', models.TextField()),
                ('activite_professionelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.activiteprofessionnelle')),
            ],
            options={
                'ordering': ['activite_professionelle'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteProfessionnelleResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('activite_professionelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.activiteprofessionnelle')),
            ],
            options={
                'ordering': ['activite_professionelle'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteProfessionnelleTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('tache', models.CharField(max_length=256)),
                ('autonomie', models.CharField(choices=[('Partielle', 'Partielle'), ('Complète', 'Complète')], default='Partielle', max_length=64)),
                ('activite_professionelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.activiteprofessionnelle')),
            ],
            options={
                'ordering': ['activite_professionelle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceCritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere_evaluation', models.TextField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.competence')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencesByActivitesProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite_professionelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.activiteprofessionnelle')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.competence')),
            ],
        ),
        migrations.AddField(
            model_name='activiteprofessionnelle',
            name='pole_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.poleactivitesprofessionnelle'),
        ),
        migrations.CreateModel(
            name='SequencePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('objectifs', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('activites', models.ManyToManyField(to='ciel_referentiel.activiteprofessionnelle')),
                ('competences', models.ManyToManyField(to='ciel_referentiel.competence')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConnaissanceAssociee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connaissance', models.CharField(max_length=256)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.competence')),
                ('taxonomie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.taxonomie')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('activite_professionelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.activiteprofessionnelle')),
                ('competence', models.ManyToManyField(to='ciel_referentiel.competence')),
                ('sequence_pedagogique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.sequencepedagogique')),
                ('type_activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciel_referentiel.typeactivitepedagogique')),
            ],
            options={
                'ordering': ['sequence_pedagogique', 'activite_professionelle'],
            },
        ),
    ]
